[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "3c3d4577ed75bc2ca0d091ba0ba087b28f7a1b3c"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "79351fbbc8b9a37d698584971d630a9fc8f07f18b35215b6eaede499811a2242"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85160b586ae28ebc947f4dc02f547486bfa44631"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "b38a6237d8f09d86de029f9cf8e6c0098daf60f8fec300758843fc5b5c806448"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e399d46939cccc945d9a14f9f58f18a9d7e5bcc"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "9c113f9850a713ac931f58990e220acfa94fde9f736443f67b866c659934eb36"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "4053da5dfb7fbce2499f2cde9c51557cb8a9f753"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "40273c0c90bfa274d0ef6a29acc2665759b481a5f6a56922eb48ce62460d7831"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "089dca6375661e6f171c5628e76b7e922cabfc61"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "aecd90cc82cc27311717f912c0ffecefcf2149d82f57c559c0105aa7b2ea0276"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "722e370249d55d8179f41eb3fae2de24d392451d"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "5df58cef7e9456c1bd3221e12534bd049a4080dabdd54c446dc41fa59d477e4b"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.i686-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02a921a7b81b962cfd616775c9f72b3bdfea8c40"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "9eee39d13cec61918c62bea837ca3ec2dcfe47f3046e5f1f375fad85ad5011c9"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "3e850e632b75258dfbb123ee5b314ad43f2ac2a6"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "8e20cc0e7d2f8c529c73bd1e31117fb56608cd9407f1bda547aac25bfa868725"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdb090eca40bca54b7cabec71a50a6c2a75d7934"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "667fb6d9e10b90a5000e228e3b81005afc7431538e47313772c1f2ee96fd46d5"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3affebc552f24a658f1663a899d1bc5243b92eb7"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "a5ca3a9b3c599e4e9b39a260e9ebc97987ef4045fb9a2ad54469f481da47b138"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "c72a56db399432050cca87897d745d5a3657d178"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "0ac197da6d0cd6fb5d3ab841717cb1555c43e9570ed41ba446d6e0a7b80aed8c"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "161a253a28cded0c07275695e15860f14744152f"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "c43d9441400685dad3593cb6a150a4b0d87ae2b37c5268661c0aa020a994d898"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "3c3d4577ed75bc2ca0d091ba0ba087b28f7a1b3c"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "79351fbbc8b9a37d698584971d630a9fc8f07f18b35215b6eaede499811a2242"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85160b586ae28ebc947f4dc02f547486bfa44631"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "b38a6237d8f09d86de029f9cf8e6c0098daf60f8fec300758843fc5b5c806448"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e399d46939cccc945d9a14f9f58f18a9d7e5bcc"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "9c113f9850a713ac931f58990e220acfa94fde9f736443f67b866c659934eb36"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "4053da5dfb7fbce2499f2cde9c51557cb8a9f753"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "40273c0c90bfa274d0ef6a29acc2665759b481a5f6a56922eb48ce62460d7831"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "089dca6375661e6f171c5628e76b7e922cabfc61"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "aecd90cc82cc27311717f912c0ffecefcf2149d82f57c559c0105aa7b2ea0276"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "722e370249d55d8179f41eb3fae2de24d392451d"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "5df58cef7e9456c1bd3221e12534bd049a4080dabdd54c446dc41fa59d477e4b"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.i686-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02a921a7b81b962cfd616775c9f72b3bdfea8c40"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "9eee39d13cec61918c62bea837ca3ec2dcfe47f3046e5f1f375fad85ad5011c9"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "3e850e632b75258dfbb123ee5b314ad43f2ac2a6"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "8e20cc0e7d2f8c529c73bd1e31117fb56608cd9407f1bda547aac25bfa868725"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdb090eca40bca54b7cabec71a50a6c2a75d7934"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "667fb6d9e10b90a5000e228e3b81005afc7431538e47313772c1f2ee96fd46d5"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3affebc552f24a658f1663a899d1bc5243b92eb7"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "a5ca3a9b3c599e4e9b39a260e9ebc97987ef4045fb9a2ad54469f481da47b138"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "c72a56db399432050cca87897d745d5a3657d178"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "0ac197da6d0cd6fb5d3ab841717cb1555c43e9570ed41ba446d6e0a7b80aed8c"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "161a253a28cded0c07275695e15860f14744152f"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "c43d9441400685dad3593cb6a150a4b0d87ae2b37c5268661c0aa020a994d898"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.0+0/TinyGismo.v0.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "df1be72cc19b341eb3641519eabb160e5840ae33"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "42d7d87530f9e4fe5b9f45a06d0be2b322ba3d7896d752644f16971a81bb4fc2"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebea81b6b45c6540c76328c84d21abed52c5de75"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "9ae1271122ebdc172a9f46043d6390c46c54b9e32bf5189b1bc2c4ab51057e5d"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6de802a050eff667ec3ce05ba02db85d8145639"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "da70636c94ef5d89a3f700a90c31f4fdf27ea72896510b23e119de618572a0df"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "aarch64"
git-tree-sha1 = "5b0a4d7e80201db7b8f7e40e0f3c4f264053b7d0"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "d216d998dfc25c359d398a7de9f0e3541e0c070957073bcbf58147c5346987da"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "524be949794fbae30f4bf3b86435eeb353570631"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "1a9424d31f131b73297fe7c7b5d79b43908a6f3b64fc24e3cb50b1d0d6a7ea0f"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfaa8e72b56acae6110dde896e3a1862b9252136"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "f4670d4633dae1ce4126f6688652d13461ed0115ca5e89e79ffebb51b34d7c79"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.i686-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4b9fc98654716cf08a778536c8c539de2ef779b"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "b5ea7831792d9dedcbb4553798591e2d114a5352efa21c16ebaaef7f4bc2d39b"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "05f6ab5c46ce0216adc23375e77e793b530d8b07"
julia_version = "1.12.0"
os = "macos"

    [[TinyGismo.download]]
    sha256 = "6689861de4a7d933971a2fb1caad2b7161beb029871cbf48a08e26ca1b1c1e50"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa959655100dcb745138ef46db8e1c6f806c57f1"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "be7c75d6175cd7e5b042c8876a610a65558815172ad0a469c25a5b54a3742cac"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc96b67f1f4738929d018df84ecde7d2471751b8"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[TinyGismo.download]]
    sha256 = "cd2a180bf3b01753360893df29e169edda30d957c1dc68699c63410795e8baa2"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
git-tree-sha1 = "c5d1017d169f55ab0af0eca2fdb1a21dbd295789"
julia_version = "1.12.0"
os = "freebsd"

    [[TinyGismo.download]]
    sha256 = "8a0dd7cf2e92d3dcdee7a1e157e523e61794287810062f10b4a1c3fcfa2f6669"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[TinyGismo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5af1fba29e55a607fdfb371e133c26a922969741"
julia_version = "1.12.0"
os = "windows"

    [[TinyGismo.download]]
    sha256 = "4560067c732c36e88593f30b4c305277bffdf8060f6cd4a12793713b4cca53bb"
    url = "https://github.com/henrij22/TinyGismo_jll.jl/releases/download/TinyGismo-v0.1.1+0/TinyGismo.v0.1.1.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
