name = "TinyGismo_jll"
uuid = "7e61441e-6e6e-5c6f-8c66-76107880e13d"
version = "0.1.10+0"

[deps]
gismo_jll = "c3015cfb-32aa-504c-ba3d-5541e7ecaf35"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "~1.11, ~1.12, ~1.13"
gismo_jll = "~25.7.0"
libcxxwrap_julia_jll = "~0.14.7"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
